development: &defaults
  adapter: postgresql
  database: restaurant_software_dev
  username: restaurant_software
  password: restaurant_software
  host: 127.0.0.1

test:
  <<: *defaults
  database: restaurant_software_test

production:
  <<: *defaults
  database: restaurant_software

